"""
AI Connect V2 — 22テーブルマッチングデータ
123名の回答者 + 234名の参加者リスト
"""

# 回答者データ（123名、重複3件除外）
# 形式: (name, chapter, category, industry, q7, q8, q9, master_row)
# master_row: マスター参加者リストのrow番号（None=未マッチ）
RESPONDENTS = [
    ("大城芳樹", "ジャンヌ", "AI顧問", "コーチング", "A", "D", "A", 88),
    ("荻原宏子", "ミリオンダラー", "外国人専門税理士", "税理士・会計士", "A", "D", "D", 6),
    ("高田廣太朗", "白樺", "印刷物・ノベルティ制作", "印刷・出版", "A", "B", "A", 122),
    ("鳥居良介", "Blossom", "International EC Marketing", "経営コンサルティング", "D", "B", "C", 113),
    ("江夏伊織", "DREAM BIG", "マグロ解体パフォーマー", "その他", "A", "B", "B", 16),
    ("前田弘樹", "INTERACT", "生命保険(法人)", "生命保険", "B", "A", "C", 20),
    ("YOO BRANDEN", "Korea Suwon Reigns", "trade", "食品製造・販売", "B", "B", "D", 138),
    ("高島徹", "ALL STARS", "時間戦略コンサル", "経営コンサルティング", "B", "A", "C", 15),
    ("上岡正和", "TRINITY(Tokyo NE?)", "タイムマシンビジネス", "経営コンサルティング", "A", "B", "A", 98),
    ("Chris Heng", "Lighthouse", "Metal/EV Manufacturer", "その他", "B", "B", "B", 222),
    ("Taehyun Kim", "Synergy", "Medical doctor/Diet clinic", "医療・クリニック", "B", "B", "A", 139),
    ("川島あいか", "ハーバー", "Instagram運用", "広告・PR", "A", "B", "D", 14),
    ("矢倉孝二", "birdie", "不動産極秘売却", "不動産売買", "C", "A", "B", 66),
    ("金光鎬 KIM KWANGHO", "トパーズ(韓国)", "文具", "その他", "A", "D", "A", 141),
    ("吉田淳一", "奈良市京都南リージョン", "BNI", "人材・組織コンサルティング", "B", "B", "A", 52),
    ("狩野善友", "Bridge ∞ Link", "個別指導塾", "学習塾・スクール", "C", "D", "A", 30),
    ("PARK WHUI JUNG", "Crown", "Cosmetic Manufacture", "その他", "B", "D", "B", 142),
    ("Danny Ng", "Lighthouse", "Automotive Metal", "その他", "B", "D", "C", 223),
    ("金子城治", "よつば", "PC修理販売", "IT機器・サポート", "B", "A", "C", 43),
    ("鮎川泰之", "クリスタル", "特定行政書士", "行政書士", "A", "A", "A", 2),
    ("高山実由紀", "インターアクト", "熟女スナック", "その他", "A", "B", "C", 23),
    ("藤本浩明", "だんじり", "イベント企画運営", "その他", "B", "B", "A", 68),
    ("Mun Dagyeong", "주얼리 제조", "주얼리 제조", "その他", "B", "C", "A", 186),
    ("金澤嘉宏", "DEER", "業務効率化×AI", "AI・DX支援", "B", "B", "C", 4),
    ("金陽信 Yangsin Kim", "ラ・トゥール", "韓国企業の支社代行", "AI・DX支援", "B", "B", "A", 62),
    ("鍋島祥郎", "Ambitious", "日本への移民送出", "人材紹介・派遣", "B", "A", "A", 59),
    ("Alex Liu", "Heat", "Human Resources Consulting", "人材・組織コンサルティング", "B", "A", "A", 164),
    ("Choijaehyuk", "Grand", "Agriculture", "AI・DX支援", "D", "C", "C", 194),
    ("忍足幸三", "Bluesky", "fortune teller", "その他", "A", "D", "D", 12),
    ("大畠英樹 OHATA HIDEKI", "Sirius", "Sightseeing taxi driver", "その他", "B", "A", "B", 108),
    ("藤本英子", "キラキラ", "景観デザインコンサル", "外構・エクステリア", "A", "B", "A", 54),
    ("Kit Chan", "Amazing (Chinese)", "Events and Exhibition", "グラフィックデザイン", "C", "A", "C", 152),
    ("栗崎由子", "Tres Stellas", "Public speaking coach", "コーチング", "A", "B", "A", 90),
    ("田上睦深", "ノーブレス", "在宅アウトソーシング", "人材紹介・派遣", "C", "C", "A", 85),
    ("横山寛", "ROUTE", "牛タン皮ジャーキー", "食品製造・販売", "B", "B", "C", 28),
    ("Chae won Yoon", "Grand Seongnam", "International trade", "医療・クリニック", "A", "A", "A", 217),
    ("Fannie Lo", "Bingo", "Spanish Restaurant", "飲食店経営", "B", "B", "C", 155),
    ("北出明日香", "ブロッサム", "インバウンド向け滞在", "その他", "A", "B", "A", 120),
    ("宮崎豊久", "ジュライズ", "開運HP制作", "Web制作・デザイン", "B", "B", "D", 13),
    ("松本大成", "東京N.E.リージョン", "パーソナルモティベーター", "研修・セミナー", "C", "B", "A", 103),
    ("安紗弥香", "Liberta", "社労士", "社会保険労務士", "C", "C", "C", 102),
    ("兵頭克典", "若鷹", "ガチャガチャ", "その他", "A", "C", "A", 24),
    ("兼城哲也", "サクシードチャプター", "書道ギャラリーバー", "グラフィックデザイン", "B", "C", "B", 38),
    ("岡健一", "ジャイアンツ", "事業計画コンサル", "経営コンサルティング", "A", "B", "A", 75),
    ("笠原麻紀", "ブロッサム", "民泊収益化プランナー", "不動産賃貸・管理", "C", "B", "B", 117),
    ("加藤千映子", "アポロ", "飲食店廃油回収", "冠婚葬祭", "A", "A", "A", 128),
    ("石川望美", "ネオシニアチャンネル", "アクティブシニアコンシェルジュ", "その他", "B", "A", "A", 78),
    ("新郷和典", "NEXIA", "Cross border consultant", "経営コンサルティング", "A", "B", "A", 127),
    ("新坂和彦", "We believe", "仲介不動産", "不動産売買", "C", "B", "B", 56),
    ("タケダ梨花 Rinka Takeda", "アルテミス", "AIコンサルタント", "AI・DX支援", "A", "B", "B", 10),
    ("大久保賢治", "トリニティ", "士業チーム作りサポート", "その他", "B", "B", "C", 95),
    ("ハンフリィス陽子", "BLOSSOM", "ハワイ不動産", "不動産売買", "B", "B", "A", 112),
    ("勝野高儀", "ブリジット", "助成金社労士", "社会保険労務士", "B", "B", "D", 91),
    ("Haydn Lau", "Supreme", "Diamond Jewelry", "ペット関連", "A", "A", "A", 159),
    ("武藤貴宏", "SR", "我武者羅應援團", "広告・PR", "B", "B", "B", 84),
    ("横山禎", "トラスト", "新市場ガイド", "経営コンサルティング", "C", "B", "A", 9),
    ("Oyuntsetseg Batmunkh", "bni nairamdal Mongolia", "Business consulting", "その他", "B", "C", "A", 221),
    ("Sosnowicz Paulina", "(individual)", "Lawyer for entrepreneurs", "弁護士", "D", "D", "D", 220),
    ("Shigeru Toyomasa", "GRIT", "社労士", "社会保険労務士", "B", "C", "B", 27),
    ("Hyodock Lee", "Crown", "Cosmetic distribution", "広告・PR", "B", "A", "A", 173),
    ("中村光輝", "フォーマル", "地域資源プロデュース", "その他", "B", "A", "A", 34),
    ("吉元大 Futoshi Yoshimoto", "Bay", "Japan Market Entry Support", "経営コンサルティング", "B", "D", "D", 107),
    ("木皿真人", "Fascinate", "錬金術師(投資)", "投資・資産運用", "B", "A", "A", 3),
    ("Phyllis Lee", "Ascend", "Japan In Depth Travel", "その他", "B", "D", "B", 193),
    ("岡村弥生", "スペクタクル", "快適住宅", "リフォーム・リノベーション", "D", "D", "A", 39),
    ("Kimchunhwa", "UNIQUE", "Aroma", "エステ・リラクゼーション", "B", "B", "C", 180),
    ("加藤博子", "宗麟", "空き家リサイクル", "その他", "C", "B", "C", 53),
    ("Tammy Sun", "BNI HK Creation", "Gifts Consultant", "印刷・出版", "A", "B", "C", 143),
    ("Millie Ho", "HK Leaders Meet", "Jewelry designer", "ペット関連", "C", "B", "C", None),
    ("田下翔太", "武蔵", "整体", "整体・鍼灸・接骨", "D", "A", "A", 70),
    ("李斌 Benny Li", "Elite", "Overseas Education", "学習塾・スクール", "C", "D", "B", 148),
    ("Ringo Lee", "Legacy", "Power Management", "AI・DX支援", "C", "D", "A", 153),
    ("Yvonne Choi", "Harvest", "Company Butler", "中小企業診断士", "B", "B", "C", 160),
    ("菅原達郎", "J-ONE", "ピアニスト", "その他", "B", "B", "C", 73),
    ("Gallant Chan", "Promising", "Biotechnological Products", "その他", "D", "D", "D", 208),
    ("石原佳史子", "アンカー", "THINGi研修", "研修・セミナー", "A", "A", "A", None),
    ("小野みか", "ウカ", "おにぎり屋", "食品製造・販売", "C", "A", "A", None),
    ("高聖雅 Shane Kao", "華資", "Business growth", "経営コンサルティング", "A", "D", "A", None),
    ("深野裕之", "白樺", "海外販路開拓", "経営コンサルティング", "A", "A", "A", 105),
    ("大原加奈子", "Anchor", "Life coach", "コーチング", "B", "A", "A", None),
    ("Yukari Suzuki", "TRES STELLAS", "Interior Art", "インテリア・内装", "B", "B", "A", None),
    ("Jack Lam", "Leaders", "Chicken paws/M&A", "投資・資産運用", "A", "A", "A", 168),
    ("長阪健久", "手筒", "金利窓口交渉", "融資・資金調達", "A", "B", "A", 47),
    ("Madlax Ho", "Empire", "Anime cultural events", "その他", "D", "D", "D", 187),
    ("Felix Poon", "Bingo", "Public speaking coach", "コーチング", "B", "A", "B", 147),
    ("高岡若葉", "ドルフィン", "マジック", "写真・映像", "C", "B", "A", None),
    ("Nicky Wai", "Harvest", "Event tech", "広告・PR", "A", "D", "A", 206),
    ("Fanny Chan", "Harvest", "Finance/Insurance", "ファイナンシャルプランナー", "B", "A", "A", 163),
    ("Jason Chan", "HARVEST", "System/Marketing", "システム開発", "A", "D", "D", 207),
    ("toshiyuki terao", "thanks！", "car parts", "自動車販売・整備", "B", "A", "A", 31),
    ("冨永恵一郎", "UNiTY", "不動産", "不動産売買", "B", "A", "C", 55),
    ("木村誠之", "S1", "IT技術サポート", "IT機器・サポート", "A", "B", "B", 101),
    ("小瀬勇太", "誉", "ネットショップ", "IT機器・サポート", "D", "A", "A", 51),
    ("岡優治", "フォーマル", "Webシステム開発", "AI・DX支援", "D", "D", "A", 35),
    ("松﨑祐子", "トレスステラ", "オフィス健康食品", "その他", "C", "D", "A", None),
    ("川井久", "S1", "ActionCOACH", "中小企業診断士", "D", "D", "D", None),
    ("Kevin Shu", "Hua Champion", "子供向けプログラミング", "学習塾・スクール", "C", "D", "D", None),
    ("鴇田英将", "SR", "ゴルフ温泉宿泊", "その他", "B", "A", "A", 89),
    ("John Zendano", "Blossom", "IT", "システム開発", "B", "D", "A", 111),
    ("上川健太郎", "Anchor", "インバウンドマーケ", "グラフィックデザイン", "A", "A", "A", None),
    ("大西弘恵", "ネオシニアチャンネル", "不動産活用コンサル", "不動産売買", "B", "D", "A", 79),
    ("稲波紀明", "ミリオンダラー", "宇宙ビジネス", "経営コンサルティング", "B", "B", "A", None),
    ("伊藤梢", "グラーノ", "英語サポート", "語学・翻訳", "C", "A", "C", 116),
    ("中島雅美", "ブロッサム", "異文化コミュコーチ", "コーチング", "B", "B", "C", 114),
    ("多久島逸平", "Blossom", "Business lawyer", "弁護士", "C", "B", "C", 118),
    ("莊婷萍", "Hua Coach Launch Ambassador", "Executive Permanence Coach", "コーチング", "B", "B", "A", None),
    ("藤間もゆか", "Bay", "Dancer", "その他", "B", "A", "B", None),
    ("内田真次", "INTERACT", "建物リフレッシュ", "リフォーム・リノベーション", "D", "B", "B", 21),
    ("桔梗 KIKYO", "ambitious", "書道家", "その他", "B", "B", "A", 60),
    ("Hsu Yilunh", "Dayan", "Designer leather bags", "その他", "B", "A", "A", 224),
    ("伏原健一郎", "エリート", "訪日旅行商品", "その他", "C", "B", "A", 209),
    ("Martin Yeung", "Leaders", "Lawyer", "弁護士", "B", "D", "D", None),
    ("栗原愛 KURIHARA MANA", "Voyage", "japanese calligraphy", "その他", "A", "D", "A", 129),
    ("Robin Chong", "Genesis (Malaysia)", "Skincare cosmetics", "その他", "A", "B", "C", 228),
    ("Tyra Tan", "Genesis", "Skincare", "その他", "B", "A", "B", 229),
    ("瀧田裕子", "アレキサンドライト", "温熱療法", "エステ・リラクゼーション", "C", "B", "A", None),
    ("Jan din", "Positive", "Makeup stylist", "美容室・ヘアサロン", "C", "B", "B", 166),
    ("Fanny Chung", "positive", "活化細胞營養品", "美容室・ヘアサロン", "D", "B", "B", 161),
    ("Derek Lai", "Dynasty", "日本のギフト", "食品製造・販売", "A", "A", "C", 165),
    ("Eric Wan", "Positive", "Industrial Equipment", "その他", "A", "D", "A", 156),
    ("Caleb Tang", "Chang An", "Skincare", "美容室・ヘアサロン", "B", "A", "B", None),
    ("Jess Cheng", "BNI HK Sunshine", "PR & Marketing", "広告・PR", "C", "B", "B", 203),
    ("Jennifer Yeung", "POSITIVE Chapter", "Foreign currency exchange", "融資・資金調達", "B", "D", "D", 232),
]

# 業種大分類マッピング
INDUSTRY_GROUPS = {
    '建築設計・施工': '建設・不動産',
    'リフォーム・リノベーション': '建設・不動産',
    '不動産売買': '建設・不動産',
    '不動産賃貸・管理': '建設・不動産',
    'インテリア・内装': '建設・不動産',
    '外構・エクステリア': '建設・不動産',
    '電気・設備工事': '建設・不動産',
    'Web制作・デザイン': 'IT・デジタル',
    'システム開発': 'IT・デジタル',
    'AI・DX支援': 'IT・デジタル',
    'SNSマーケティング': 'IT・デジタル',
    '動画制作・映像': 'IT・デジタル',
    'IT機器・サポート': 'IT・デジタル',
    '弁護士': '士業・コンサルティング',
    '税理士・会計士': '士業・コンサルティング',
    '社会保険労務士': '士業・コンサルティング',
    '行政書士': '士業・コンサルティング',
    '中小企業診断士': '士業・コンサルティング',
    '経営コンサルティング': '士業・コンサルティング',
    '人材・組織コンサルティング': '士業・コンサルティング',
    '生命保険': '金融・保険',
    'ファイナンシャルプランナー': '金融・保険',
    '融資・資金調達': '金融・保険',
    '投資・資産運用': '金融・保険',
    '美容室・ヘアサロン': '美容・健康',
    'エステ・リラクゼーション': '美容・健康',
    '整体・鍼灸・接骨': '美容・健康',
    '医療・クリニック': '美容・健康',
    '飲食店経営': '飲食・食品',
    '食品製造・販売': '飲食・食品',
    '語学・翻訳': '教育・研修',
    '研修・セミナー': '教育・研修',
    'コーチング': '教育・研修',
    '学習塾・スクール': '教育・研修',
    'グラフィックデザイン': 'クリエイティブ',
    '写真・映像': 'クリエイティブ',
    '印刷・出版': 'クリエイティブ',
    '冠婚葬祭': '生活サービス',
    'ペット関連': '生活サービス',
    '自動車販売・整備': '生活サービス',
    '人材紹介・派遣': 'その他',
    '広告・PR': 'その他',
    'その他': 'その他',
}

ANSWER_MAP = {'A': 'D', 'B': 'I', 'C': 'S', 'D': 'C'}
