#!/usr/bin/env python3
"""
未回答者 (master 234 - 110 確認済respondents = 124名) のリスト
形式: (region, surname, given, country, ticket_type, master_row)
"""

# Master "インターナショナルウェルカムイブニング" tabより
# 回答済rows: [2,3,4,6,9,10,12,13,14,15,16,20,21,23,24,27,28,30,31,34,35,38,39,43,47,51,52,53,54,55,56,59,60,62,66,68,70,73,75,78,79,84,85,88,89,90,91,95,98,101,102,103,105,107,108,111,112,113,114,116,117,118,120,122,127,128,129,138,139,141,142,143,147,148,152,153,155,156,159,160,161,163,164,165,166,168,173,180,186,187,193,194,203,206,207,208,209,217,220,221,222,223,224,228,229,232]

UNANSWERED = [
    # 日本リージョン (master rows 5,7,8,11,17,18,19,22,25,26,29,32,33,36,37,40,41,42,44,45,46,48,49,50,57,58,61,63,64,65,67,69,71,72,74,76,77,80,81,82,83,86,87,92,93,94,96,97,99,100,104,106,109,110,115,119,121,123,124,125,126,130)
    ("BNI Osaka North West", "原田", "実", "Japan", "BNIメンバー", 5),
    ("BNI Tokyo Minato Chuo", "大竹", "通孝", "Japan", "BNIメンバー", 7),
    ("BNI Tokyo NE", "近藤", "哲生", "Japan", "BNIメンバー", 8),
    ("BNI Yokohama Central", "Alfred Wong", "", "Japan", "BNIメンバー", 11),
    ("Fukui", "大澤", "義人", "日本", "Member", 17),
    ("Fukui", "水上", "心", "日本", "Member", 18),
    ("Fukui", "小林", "宏崇", "日本", "Member", 19),
    ("Fukui", "山本", "斉", "日本", "Member", 22),
    ("Gunma East", "Iketsu", "Kazuko", "日本", "Regional Leader", 25),
    ("Gunma East", "前田", "和宏", "日本", "Director", 26),
    ("Kitakyushu East", "狩野", "博司", "日本", "Regional Leader", 29),
    ("Kobe East", "KOINUMA", "JUNYA", "日本", "Member", 32),
    ("Kumamoto City", "松尾", "美佳", "日本", "Member", 33),
    ("Kumamoto City", "住永", "和子", "日本", "Member", 36),
    ("Kumamoto City", "上杉", "彩加", "日本", "Member", 37),
    ("Kyoto City Central", "小木曽", "貴弘", "日本", "Regional Leader", 40),
    ("Kyoto City Central", "原田", "正規", "日本", "Member", 41),
    ("Kyoto City Central", "赤坂", "城二", "日本", "Member", 42),
    ("Mikawa East", "笹野", "将治", "日本", "Member", 44),
    ("Mikawa East", "大久保", "邦恵", "日本", "Member", 45),
    ("Mikawa East", "柴谷", "幸子", "日本", "Member", 46),
    ("Nagoya Central", "MICHIGAMI", "KAZUKI", "日本", "Member", 48),
    ("Nagoya Central", "古田", "将人", "日本", "Member", 49),
    ("Nagoya SE", "清水", "エリザベス", "日本", "Member", 50),
    ("Osaka City North", "藤田", "慎二", "日本", "Member", 57),
    ("Osaka City North", "中野", "陽介", "日本", "Member", 58),
    ("Osaka City North", "有田 ARITA", "武史 TAKESHI", "日本", "Member", 61),
    ("Osaka East", "福﨑", "二郎", "日本", "Member", 63),
    ("Osaka East", "田中", "桃子", "日本", "Member", 64),
    ("Osaka East", "木曽", "稚彗", "日本", "Member", 65),
    ("Osaka East", "内田", "高史", "日本", "Member", 67),
    ("Osaka North East", "中村", "優志", "日本", "Member", 69),
    ("Tama East", "Nakajima", "Hiroshi", "日本", "Director", 71),
    ("Tama East", "組田", "裕也", "日本", "Member", 72),
    ("Tokyo BC", "虎岩", "雅明", "日本", "Regional Leader", 74),
    ("Tokyo BC", "宇佐神", "悟", "日本", "Director", 76),
    ("Tokyo BC", "秋本", "圭介", "日本", "Member", 77),
    ("Tokyo Chiyoda", "岸", "宏保", "日本", "Member", 80),
    ("Tokyo Chuo East", "川合", "彰", "日本", "Member", 81),
    ("Tokyo Minato Chuo", "滝澤", "宗之", "日本", "Member", 82),
    ("Tokyo Minato Chuo", "山崎", "純代", "日本", "Director", 83),
    ("Tokyo Minato Chuo", "周", "泰維", "日本", "Member", 86),
    ("Tokyo Minato Chuo", "仁藤", "かほり", "日本", "Member", 87),
    ("Tokyo NE", "仁平", "義彦", "日本", "Member", 92),
    ("Tokyo NE", "MAKIKO", "KIDA", "日本", "Member", 93),
    ("Tokyo NE", "藤田", "覚", "日本", "Member", 94),
    ("Tokyo NE", "Sayama", "Yosuke", "日本", "Member", 96),
    ("Tokyo NE", "渡邉", "拓未", "日本", "Member", 97),
    ("Tokyo Shibuya", "秋澤", "真澄", "日本", "Member", 99),
    ("Tokyo Shibuya", "李", "爽", "日本", "Member", 100),
    ("Yokohama Central", "Kaori", "Tanigawa", "日本", "Director", 104),
    ("Yokohama Central", "TOJI", "KAZUYA", "日本", "Director", 106),
    ("Yokohama Central", "Chen", "Sky", "日本", "Member", 109),
    ("Yokohama Central", "Christ", "Nick", "日本", "Member", 110),
    ("Yokohama Central", "須藤", "聡美", "日本", "Member", 115),
    ("Yokohama Central", "瀬田", "勇一", "日本", "Member", 119),
    ("Yokohama Central", "Yamawaki", "Alisa", "日本", "Member", 121),
    ("Yokohama Central", "大内", "秀", "日本", "Member", 123),
    ("Yokohama Central", "あらい", "ひとみ", "日本", "Member", 124),
    ("Yokohama Central", "UBE", "KOTA", "日本", "Member", 125),
    ("Yokohama Central", "Sakamoto", "Alex", "日本", "Member", 126),
    ("Yokohama Central", "山田", "研二", "日本", "Member", 130),
    # ビジター
    ("ビジター", "Heiser", "Alan", "Australia", "Visitor", 131),
    ("ビジター", "IMAMURA", "KENJI", "日本", "Visitor", 132),
    ("ビジター", "豊政", "温子", "Japan", "ビジター", 133),
    # Overseas (rows 134-235、回答済除く)
    ("Overseas Taiwan", "Chung", "Jenny", "台湾", "Director", 134),
    ("Overseas Taiwan", "TANG", "KEA MING", "台湾", "Member", 135),
    ("Overseas Taiwan", "Liu", "Allie", "台湾", "Member", 136),
    ("Overseas Taiwan", "Liu", "Milene", "台湾", "Visitor", 137),
    ("Overseas Taiwan", "Yang", "Yueh Lin", "台湾", "Member", 140),
    ("Overseas HK", "Yeung", "Wan Fung", "香港", "Member", 144),
    ("Overseas HK", "Wendy", "Man", "香港", "Member", 145),
    ("Overseas HK", "Lo", "Sam", "香港", "Member", 146),
    ("Overseas HK", "Suen", "Rony", "香港", "Member", 149),
    ("Overseas HK", "Man", "Alan", "香港", "Member", 150),
    ("Overseas HK", "Lee", "Sing", "香港", "Member", 151),
    ("Overseas HK", "Huang", "Dora", "香港", "Member", 154),
    ("Overseas HK", "Chow", "Joyce", "香港", "Member", 157),
    ("Overseas HK", "Cheung", "Kammy", "香港", "Member", 158),
    ("Overseas HK", "Lam", "Jon", "香港", "Member", 162),
    ("Overseas HK", "Li", "Yoyo", "香港", "Member", 167),
    ("Overseas HK", "Huang", "Simon", "香港", "Member", 169),
    ("Overseas HK", "Chang", "James", "香港", "Member", 170),
    ("Overseas HK", "Li", "Phyllis", "香港", "Member", 171),
    ("Overseas HK", "Ho", "Jeff", "香港", "Member", 172),
    ("Overseas Korea", "チウン", "ユン", "韓国", "Member", 175),
    ("Overseas Taiwan", "Yu", "Nilson", "台湾", "Member", 176),
    ("Overseas Taiwan", "CHIU", "MINGYU", "台湾", "Member", 177),
    ("Overseas Korea", "Kong", "Jinwook", "韓国", "Member", 178),
    ("Overseas Korea", "KIM", "SUNJOONG", "韓国", "Member", 179),
    ("Overseas Korea", "복", "혜영", "韓国", "Visitor", 181),
    ("Overseas Mongolia", "Ganzorig", "DUNJINGARAV", "Mongolia", "Member", 182),
    ("Overseas China", "JIN", "JINGHUAN", "中国", "Member", 183),
    ("Overseas Korea", "Choi", "Miyeon", "韓国", "Member", 184),
    ("Overseas Korea", "Park", "Eun-Kyung", "韓国", "Member", 185),
    ("Overseas Korea", "KWON", "JINHEE", "韓国", "Member", 188),
    ("Overseas Thailand", "Thalerngnawachart", "Kollakit", "Thailand", "ND", 189),
    ("Overseas Thailand", "Thalerngnawachart", "Wanna", "Thailand", "ND", 190),
    ("Overseas China", "XU", "CHAOHUI", "中国", "Member", 191),
    ("Overseas Taiwan", "Xie", "Smart", "台湾", "ND", 192),
    ("Overseas USA", "PHILLIPS", "Christopher", "USA", "Member", 195),
    ("Overseas HK", "Wong", "Ann", "香港", "Member", 196),
    ("Overseas Taiwan", "Cheung", "Hoi Hang Vera", "台湾", "Member", 197),
    ("Overseas HK", "Huang", "Howard", "香港", "Visitor", 198),
    ("Overseas HK", "Lam", "Yan na", "香港", "Visitor", 199),
    ("Overseas HK", "Leung", "James", "香港", "Member", 200),
    ("Overseas HK", "Ho", "Louis", "香港", "Member", 201),
    ("Overseas HK", "Chau", "Bryant", "香港", "Member", 202),
    ("Overseas HK", "Chan", "Kim", "香港", "Member", 204),
    ("Overseas HK", "Lau", "Lokki", "香港", "Member", 205),
    ("Overseas Mongolia", "Byambaragchaa", "Tegshzaya", "Mongolia", "Visitor", 210),
    ("Overseas Taiwan", "林", "文偉", "台湾", "Member", 211),
    ("Overseas HK", "Yung", "Stella", "香港", "ND", 212),
    ("Overseas HK", "Kong", "Stanley", "香港", "ND", 213),
    ("Overseas Korea", "LEE", "MYUNGJONG", "韓国", "Member", 214),
    ("Overseas Korea", "Sumgjin", "Ju", "韓国", "Member", 215),
    ("Overseas Korea", "Go", "hyungcheol", "韓国", "Member", 216),
    ("Overseas Singapore", "Leong", "Wilfred", "Singapore", "Visitor", 218),
    ("Overseas HK", "Fung", "Angus", "香港", "Member", 219),
    ("Overseas Malaysia", "Samantha Chee", "", "Malaysia", "BNI", 225),
    ("Overseas Malaysia", "Renee ho", "", "Malaysia", "BNI", 226),
    ("Overseas Malaysia", "Cheong Ming Yan", "", "Malaysia", "BNI", 227),
    ("Overseas Malaysia", "Barry Ng", "", "Malaysia", "BNI", 230),
    ("Overseas HK", "jeffrey yu", "", "Hong Kong", "BNI", 231),
    ("Overseas Malaysia", "GOH HUI LING", "", "Malaysia", "BNI", 233),
    ("Overseas HK", "Kuong Kiu Yung", "Candy", "Hong Kong", "Visitor", 234),
    ("Overseas HK", "Tong Pak Kin Simon", "", "Hong Kong", "Visitor", 235),
]

import sys
if __name__ == '__main__':
    print(f"Total UNANSWERED: {len(UNANSWERED)}", file=sys.stderr)
